// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyrcbjsoszezgwsoxdzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cmNianNvc3plemd3c294ZHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMDAyNTUsImV4cCI6MjA4Nzg3NjI1NX0.vikZfb67xUVmtoFvjQDfbmFIu3x4dAdoTbAGP5wMYzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});