// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnriaigsdmnscfmrlbrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucmlhaWdzZG1uc2NmbXJsYnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMzIyNTIsImV4cCI6MjA4NzcwODI1Mn0.dLXT-ZZsFfzeA7a3iIiNRzh1D2Xdnlobkd0D8s0DzuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});